# Generated by Django 6.0.7 on 2026-07-13 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('company_name', models.CharField(blank=True, help_text='Optional', max_length=200)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_type', models.CharField(help_text='e.g. Laptop, Printer, CCTV', max_length=100)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('details', models.TextField(blank=True, help_text='Any other identifying details')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='service.client')),
            ],
        ),
        migrations.CreateModel(
            name='RepairJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_number', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('date_in', models.DateField()),
                ('received_by', models.CharField(help_text='Who brought the machine in', max_length=150)),
                ('problem_cause', models.TextField(help_text='Problem / cause reported at intake')),
                ('date_out', models.DateField(blank=True, null=True)),
                ('solution_detail', models.TextField(blank=True)),
                ('taken_by', models.CharField(blank=True, help_text='Who collected the machine', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repair_jobs', to='service.client')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repair_jobs', to='service.machine')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WarrantyClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_number', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('date_in', models.DateField()),
                ('received_by', models.CharField(max_length=150)),
                ('bought_from', models.CharField(blank=True, max_length=200)),
                ('warranty_sent_date', models.DateField(blank=True, help_text='Editable', null=True)),
                ('claimable', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=10)),
                ('report_warranty_claimed', models.TextField(blank=True, help_text='Filled if claimable = Yes')),
                ('solved', models.CharField(blank=True, choices=[('solved', 'Solved'), ('not_solved', 'Not Solved')], max_length=15)),
                ('not_solved_cause', models.TextField(blank=True, help_text='Required if not solved')),
                ('sent_date_out', models.DateField(blank=True, null=True)),
                ('report_complete', models.BooleanField(default=False, help_text='Complete or not')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warranty_claims', to='service.machine')),
                ('sold_to', models.ForeignKey(help_text='Client details', on_delete=django.db.models.deletion.PROTECT, related_name='warranty_claims', to='service.client')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
