# Generated by Django 6.0.7 on 2026-08-07 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_create_repair_warranty_groups'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['name', 'company_name']},
        ),
        migrations.AlterField(
            model_name='client',
            name='company_name',
            field=models.CharField(blank=True, help_text='Company or organisation name (optional if contact name provided)', max_length=200),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(blank=True, help_text='Contact person name (optional if company name provided)', max_length=200),
        ),
        migrations.AlterField(
            model_name='warrantyclaim',
            name='claimable',
            field=models.CharField(blank=True, choices=[('yes', 'Approved'), ('no', 'Rejected')], max_length=10),
        ),
    ]
