# Generated by Django 6.0.7 on 2026-08-12 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_client_name_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='warrantyclaim',
            name='sent_by',
            field=models.CharField(blank=True, help_text='Staff member who delivered the machine to the distributor/manufacturer', max_length=150),
        ),
        migrations.AddField(
            model_name='warrantyclaim',
            name='taken_by',
            field=models.CharField(blank=True, help_text='Who collected the machine after the claim was resolved', max_length=150),
        ),
    ]
